name: Proto Gen

on:
  pull_request:
    paths-ignore:
      - "lib/**"
  push:
    branches:
      - master
    paths-ignore:
      - "lib/**"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v2.1.0"
      - uses: "cachix/install-nix-action@v10"
        with:
          skip_adding_nixpkgs_channel: true
      - uses: "cachix/cachix-action@v6"
        with:
          name: hpulsar
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: "Build protobuf generator 🚧"
        run: cd proto && nix-shell --run "cabal new-build" && cd ..
